### PR TITLE
v3.3.0 compatible client

### PR DESCRIPTION
**Pull request by holmesb**
Main challenge was profiles; `ValueErrored` unless their name field was written before the rest.  A few schema changes, plus Ubuntu 20.04 replacing 18.04.
go run cmd/main.go is now executing to completion and all acceptance tests are passing.  Removed COBBLER_FIELDS.md doc since too great a maintenance burden to track the Cobbler schema here; a more [up-to-date reference](https://cobbler.github.io/cobbler-web/) is available.
Two known issues:
1.  Systems cannot currently have interfaces attached due to Cobbler issue #2846, should be fixed in next minor release.
2.  Bootloader cannot be configured.  Will create a new issue for this upon merge and do this next

### CODE REVIEW

**Comment by SchoolGuy** [comment]
@holmesb What is missing to make this PR pass the tests?

Additionally: Are you sure that the changed import order is correct? So did you run `go fmt` on those files?

**Comment by holmesb** [comment]
github actions tests are now passing.  Yes my IDE automatically runs `go fmt`.  Import order doesn't make any difference to this client, but I've reset the order back to same as main branch

**Review by SchoolGuy — APPROVED** [review]
LGTM

**Comment by SchoolGuy** [comment]
@holmesb This missing backward compatibility we can solve on another day. Thanks for making this possible!

**Comment by holmesb** [comment]
@SchoolGuy, thx for merging.  Think this needs a new release to be referred from the terraform provider.  Pls could you create a release v0.5.0?

**Comment by SchoolGuy** [comment]
@holmesb Sure thing. Do you want to work on your second issue before I create the tag or afterwards?

**Comment by holmesb** [comment]
Ok can hang tight, I'll have a crack at bootloader later this week.  Might not be a terraform\go client issue, but I'll figure either way.

**Pull request merged**
