### PR TITLE
Added support for bootloaders in system.go & distro.go

### PR DESCRIPTION
**Pull request by holmesb**
Should be good for the 0.5.0 release now

### CODE REVIEW

**Review by SchoolGuy — APPROVED** [review]
LGTM

**Comment by SchoolGuy** [comment]
Will tag on the weekend after some testing I am doing then hopefully.

**Comment by holmesb** [comment]
Thx @SchoolGuy, be great if you could prioritise Cobbler issue [#2846](https://github.com/cobbler/cobbler/issues/2846) (fix interfaces via XMLRPC) because this client is pretty useless without (as is Terraform)

**Comment by SchoolGuy** [comment]
@holmesb Sure thing. I will do my best.

**Pull request merged**
